/*******************************************************************
        SYSTEM LampSystem
        Module for PROCESS Button
        Filename: Button.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LampUnit 
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mLampUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Button.write_access_
#define STATUS (pStatus_Button->read_access_)
#define TIME time_LampUnit

/* Process Enumerations */

enum eMODES_Button
	{normal = 1};

enum eSTATES_Button
	{Pushed = 1, Released};


/* External Declarations */

extern unsigned char time_LampUnit;
extern struct tCHNOUT_mLampUnit CHNOUT_mLampUnit;
void fUPDATE_LampCluster (void);
int fPULSE_Lamp (enum eOUTPLS_LampUnit name_);

/* Global Declarations */

union tSTATUS_Button status_Button;
const union tSTATUS_Button *pStatus_Button = &status_Button;

/* Function Prototypes */

void fIMSG_C1_Push(void);
void fIMSG_C1_Release(void);
void fINIT_Button (void);

/* Input Channel Functions */

void fIMSG_C1_Push(void)
{
	switch(status_Button.read_access_.STATE)
	{
	case Released:
	 	status_Button.write_access_.STATE = Pushed;
	 	fPULSE_Lamp (O1_On);
		break;
	default:
		return;
	}
	fUPDATE_LampCluster ();
	return;
}

void fIMSG_C1_Release(void)
{
	switch(status_Button.read_access_.STATE)
	{
	case Pushed:
	 	status_Button.write_access_.STATE = Released;
	 	fPULSE_Lamp (O1_Off);
		break;
	default:
		return;
	}
	fUPDATE_LampCluster ();
	return;
}
		
/* Process Initialization Function */

void fINIT_Button (void)
{
	status_Button.write_access_.STATE = Released;
}		

/*********************************************************************
	End of Module for PROCESS Button
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,2898f6bd-ef75-11ef-aef2-9dc0ca6165d0,2898f691-ef75-11ef-aef2-9dc0ca6165d0,ZbBgT6IpeCHN98jArL+nrsnYLCQ=] */
