/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Error Header File for CIP MACHINE mLampUnit
	Filename: eLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_eLampUnit_hLampUnit_)
	#define _eLampUnit_hLampUnit_

/* Include Files */

#include "mLampUnit.h"

#endif // _eLampUnit_hLampUnit_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,wysmq+6+tpUKAMksbKUt+mqypAY=] */
