/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Error Interface Module for CIP MACHINE mLampUnit
	Filename: eLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "eLampUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,IR+PnFLzXFjuyj5zttG5Ac/8UUc=] */
