/*******************************************************************
        SYSTEM LampSystem
        Module for PROCESS Lamp
        Filename: Lamp.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LampUnit 
        	enable PENDING_ information
        	incremental build
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mLampUnit.h"

/* Process Macro Definitions */

#define SELF status_Lamp.write_access_
#define STATUS (pStatus_Lamp->read_access_)
#define TIME time_LampUnit

/* Process Enumerations */

enum eMODES_Lamp
	{normal = 1};

enum eSTATES_Lamp
	{Bright = 1, Dark, Delayed};

enum eINPULS_Lamp
	{IP_On = 1, IP_Off, TIMEUP_};
	

/* External Declarations */

extern unsigned char time_LampUnit;
extern struct tTMQE_mLampUnit *tuhead_mLampUnit, *tutail_mLampUnit;
extern struct tCHNOUT_mLampUnit CHNOUT_mLampUnit;
extern struct tTIMING_mLampUnit TIMING_mLampUnit[TIMER_COUNT_LampUnit];
void fUPDATE_LampCluster (void);
void fSETTIM_mLampUnit (unsigned char *delay_, struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_);
void fSTOPTIM_mLampUnit (struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_);

/* Global Declarations */

static unsigned char delay_;
struct tPRINST_Lamp IO_Lamp;
union tSTATUS_Lamp status_Lamp;
const union tSTATUS_Lamp *pStatus_Lamp = &status_Lamp;

/* Function Prototypes */

int fPULSE_Lamp (enum eOUTPLS_LampUnit name_);
void fINIT_Lamp (void);

/* Input Channel Functions */

int fPULSE_Lamp (enum eOUTPLS_LampUnit name_)
{
	switch(name_)
	{
		/* INPULSE On */
	case O1_On:		/* PULSE CAST from PROCESS Button */
		switch(status_Lamp.read_access_.STATE)
		{
		case Dark:
			status_Lamp.write_access_.STATE = Bright;
			CHNOUT_mLampUnit.message_.CHAN_Lamp.name_ = C2_Bright;
			OUT_LampUnit.C2_Bright ();
			break;
		case Delayed:
			status_Lamp.write_access_.STATE = Bright;
			break;
		default:
			break;
		}
		break;
		/* INPULSE Off */
	case O1_Off:		/* PULSE CAST from PROCESS Button */
		switch(status_Lamp.read_access_.STATE)
		{
		case Bright:
			{
				delay_ =  3;	/* DELAY 3 */
				status_Lamp.write_access_.STATE = Delayed;
				fSETTIM_mLampUnit(&delay_, 
					&IO_Lamp.timer_, 
					&IO_Lamp.timeup_);
			}
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Lamp (void)
{
	if (IO_Lamp.timer_.set_ &&
		IO_Lamp.timer_.end_ == time_LampUnit)
	{
		IO_Lamp.timer_.set_ = FALSE;
		--TIMING_mLampUnit[TIMER_Lamp_2].set_;
		if (tuhead_mLampUnit != &IO_Lamp.timeup_ &&
			!IO_Lamp.timeup_.preced_ &&
			!IO_Lamp.timeup_.next_)
		{
			if (!tuhead_mLampUnit)
			{
				tuhead_mLampUnit = tutail_mLampUnit = &IO_Lamp.timeup_;
			}
			else
			{
				tutail_mLampUnit->next_ = &IO_Lamp.timeup_;
				IO_Lamp.timeup_.preced_ = tutail_mLampUnit;
				tutail_mLampUnit = &IO_Lamp.timeup_;
			}
		}
	}			
}

static void fTUHNDL_Lamp(void)
{
	struct tTMQE_mLampUnit *element_ = tuhead_mLampUnit;
	if (tuhead_mLampUnit == tutail_mLampUnit)
	{
		tuhead_mLampUnit = tutail_mLampUnit = 0;
	}
	else 
	{
		tuhead_mLampUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mLampUnit->preced_ = 0;
	}
	switch(status_Lamp.read_access_.STATE)
	{
	case Delayed:
		status_Lamp.write_access_.STATE = Dark;
		CHNOUT_mLampUnit.message_.CHAN_Lamp.name_ = C2_Dark;
		OUT_LampUnit.C2_Dark ();
		break;
	default:
		break;
	}
	fUPDATE_LampCluster (); 
}

/* Process Initialization Function */

void fINIT_Lamp (void)
{
	status_Lamp.write_access_.STATE = Dark;
	IO_Lamp.timer_.set_ = FALSE;
	IO_Lamp.timeup_.preced_ = 0;
	IO_Lamp.timeup_.next_ = 0;
	IO_Lamp.timeup_.proctype_ = TIMER_Lamp_2;
	TIMING_mLampUnit[TIMER_Lamp_2].tkhndl_ = fTICK_Lamp;
	TIMING_mLampUnit[TIMER_Lamp_2].tuhndl_ = fTUHNDL_Lamp;
}		

/*********************************************************************
	End of Module for PROCESS Lamp
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,2898f6bd-ef75-11ef-aef2-9dc0ca6165d0,2898f6ac-ef75-11ef-aef2-9dc0ca6165d0,H0oPqguuc3ZV4OtzFQ4AuUHyV2Q=] */
