/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Header File for CIP MACHINE mLampUnit
	Filename: mLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_mLampUnit_hLampUnit_)
	#define _mLampUnit_hLampUnit_

/* Include Files */

#include <stdlib.h>
#include "sLampUnit.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Timer Types*/

#if !defined(TIMER_C_COUNT_LampUnit)
	#define TIMER_C_COUNT_LampUnit 1
#endif // TIMER_C_COUNT_LampUnit

#if !defined(_eTIMER_LampUnit_)
	#define _eTIMER_LampUnit_

	enum _eTIMER_LampUnit
		{TIMER_Lamp_2, TIMER_COUNT_LampUnit};

#endif // _eTIMER_LampUnit_

/* Outpulse Types */
 
#if !defined(_eOUTPLS_LampUnit_)
	#define _eOUTPLS_LampUnit_

	enum eOUTPLS_LampUnit
		{/* LampCluster */ O1_On = 1, O1_Off};

#endif // _eOUTPLS_LampUnit_

struct tOUTPLS_Button
{
	enum eOUTPLS_LampUnit name_;
};

union tOUTPLS_LampCluster
{
	struct tOUTPLS_Button OUTPLS_Button;
};

/* Global Output Type */

struct tCHAN_Lamp
{
	enum eMSG_Lamp name_;
};

union tCHAN_mLampUnit
{
	struct tCHAN_Lamp CHAN_Lamp;
};

struct tCHNOUT_mLampUnit
{
	union tCHAN_mLampUnit message_;
};

/* Timer- and Queue-Element */

struct tTMEL_mLampUnit
{
	unsigned char set_; /* Boolean */
	unsigned char end_;
};

struct tTMQE_mLampUnit
{
	struct tTMQE_mLampUnit *preced_;
	struct tTMQE_mLampUnit *next_;
	int proctype_;
};

/* Global Table Elements */
struct tTIMING_mLampUnit
{
	void  (*tkhndl_) (void);
	void (*tuhndl_)(void);
	int  set_;
};

/* Types for Process Button */

struct tPRSTAT_Button
{
	int STATE;
};

union tSTATUS_Button
{
	struct tPRSTAT_Button write_access_;
	struct tPRSTAT_Button read_access_;
};

/* Types for Process Lamp */

struct tPRSTAT_Lamp
{
	int STATE;
};

union tSTATUS_Lamp
{
	struct tPRSTAT_Lamp write_access_;
	struct tPRSTAT_Lamp read_access_;
};

struct tPRINST_Lamp
{
	struct tTMEL_mLampUnit timer_;
	struct tTMQE_mLampUnit timeup_;
};

#endif // _mLampUnit_hLampUnit_

/*********************************************************************
	End of Header File for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6bf-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,TJBzCxNLdM55kf9DcsgD2/GddG8=] */
