/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Module for CIP SHELL sLampUnit
	Filename: sLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "sLampUnit.h"

/* Input Interface */

struct tIN_LampUnit IN_LampUnit;

/* Output Interface */

struct tOUT_LampUnit OUT_LampUnit;

/* Trigger Interface */

struct tTRG_LampUnit TRG_LampUnit;

/*********************************************************************
	End of Module for CIP SHELL sLampUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,2898f6bf-ef75-11ef-aef2-9dc0ca6165d0,GA/IjsKphmqm+gIQlQINmpxJ6GU=] */
