/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Header File for CIP SHELL sLampUnit
	Filename: sLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_sLampUnit_hLampUnit_)
	#define _sLampUnit_hLampUnit_
/* Code Option Constants */

#if defined(_EINPUT__)
	#undef _EINPUT__
#endif 

#if !defined(_PENDING__)
	#define _PENDING__
#endif 

/* Channel Enumerations */

#if !defined(_eCHAN_LampUnit_)
	#define _eCHAN_LampUnit_

	enum eCHAN_LampUnit
		{C_Button = 1, C_Lamp = 2};

#endif // _eCHAN_LampUnit_

/*********************************************************************
	CODE  GENERATION  FEATURE
	This global message enumeration can be used 
	for implementation purposes.
*********************************************************************/

enum eMSG_LampUnitLampUnit
	{F_C1_Push_ = 1, F_C1_Release_ = 2, F_C2_Bright_ = 3, F_C2_Dark_ = 4};

/********************************************************************/

#if !defined(_eMSG_Button_)
	#define _eMSG_Button_

	enum eMSG_Button
		{C1_Push = 1, C1_Release = 2};

#endif // _eMSG_Button_

#if !defined(_eMSG_Lamp_)
	#define _eMSG_Lamp_

	enum eMSG_Lamp
		{C2_Bright = 1, C2_Dark = 2};

#endif // _eMSG_Lamp_

/* Input Interface Type */

struct tIN_LampUnit
{
	void (*C1_Push)(void);
	void (*C1_Release)(void);
};

/* Output Interface Type */

struct tOUT_LampUnit
{
	void (*C2_Bright)(void);
	void (*C2_Dark)(void);
};


/* Trigger Interface Type */

#if !defined(_tPENDING__)
	#define _tPENDING__
	
	struct tPENDING_
	{
		int ANY_;	/* boolean indicating any pending transitions */
		int CHAIN_;	/* boolean indicating pending CHAIN_ */
		int TIMEUP_;	/* boolean indicating pending TIMEUP_ */
		int READ_;	/* boolean indicating buffered internal message */
		int AUTO_;	/* boolean indicating reading AUTO_ */
	};
	
#endif // _tPENDING__

struct tTRG_LampUnit
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/*  trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
	struct tPENDING_ PENDING_;		/* information on pending transitions */
};

/* External Interface Declarations */

extern struct tIN_LampUnit IN_LampUnit;		/* Input Channel Interface defined in sLampUnit.c */
extern struct tOUT_LampUnit OUT_LampUnit;		/* Output Channel Interface defined in sLampUnit.c */
extern struct tTRG_LampUnit TRG_LampUnit;		/* Trigger Interface defined in sLampUnit.c */

/* Unit Initialization Function, defined in mLampUnit.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_LampUnit(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iMSG_LampUnit(void);

#endif // _sLampUnit_hLampUnit_

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sLampUnit
*********************************************************************/
/* Actifsource ID=[b7934a9b-259a-11e1-ae2f-a14f3e396de6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,2898f6bf-ef75-11ef-aef2-9dc0ca6165d0,zeSlDOnOuMeMR7a1P/aaa1vNF/w=] */
