/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION  LampImplementation
	Trace Interface Header File for CIP MACHINE mLampUnit
	Filename: tLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

#if !defined(_tLampUnit_hLampUnit_)
	#define _tLampUnit_hLampUnit_

/* Include Files */

#include "mLampUnit.h"

#endif // _tLampUnit_hLampUnit_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,5xaNOWXKgVlrgbrF6WT8d0QeTnw=] */
