/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Trace Interface Module for CIP MACHINE mLampUnit
	Filename: tLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampUnit 
		enable PENDING_ information
		incremental build
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "tLampUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,2898f6c0-ef75-11ef-aef2-9dc0ca6165d0,2898f67e-ef75-11ef-aef2-9dc0ca6165d0,2898f6d3-ef75-11ef-aef2-9dc0ca6165d0,2898f6be-ef75-11ef-aef2-9dc0ca6165d0,TlFXYSyswLZeNqrCfQ0A/jVr4dc=] */
