/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Error Interface Module for CIP MACHINE mLampUnit
	Filename: eLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "eLampUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mLampUnit
*********************************************************************/

// Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,0e3da843-613c-11e2-8c6f-0d0126f0c0ea,16966e79-613e-11e2-8c6f-0d0126f0c0ea,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,16997bbd-613e-11e2-8c6f-0d0126f0c0ea,C/KTxJZ/+ScApTipphCIFbAP3UY=]
