/*********************************************************************
	SYSTEM Lamp_CipSystem
	IMPLEMENTATION LampImplementation
	Error Interface Module for CIP MACHINE mLampUnit
	Filename: eLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "eLampUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,dc0ccb3f-eeb2-11ef-a3fc-b5c521c52e06,bc124dc7-eea7-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,dc109bd3-eeb2-11ef-a3fc-b5c521c52e06,7omPtLG0+zJoCZog/aaKpjppdBQ=] */
