/*********************************************************************
	SYSTEM Lamp_CipSystem
	IMPLEMENTATION LampImplementation
	Error Header File for CIP MACHINE mLampUnit
	Filename: eLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_eLampUnit_h_)
	#define _eLampUnit_h_

/* Include Files */

#include "mLampUnit.h"

#endif // _eLampUnit_h_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,dc0ccb3f-eeb2-11ef-a3fc-b5c521c52e06,bc124dc7-eea7-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,dc109bd3-eeb2-11ef-a3fc-b5c521c52e06,ecwhL/c3byQLXixecK3663Ee7Wo=] */
