/*********************************************************************
	SYSTEM Lamp_CipSystem
	IMPLEMENTATION LampImplementation
	Module for CIP MACHINE mLampUnit
	Filename: mLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mLampUnit.h"

/* External Declarations */

void fICHAN_Button (enum eMSG_Button name_);
void fINIT_Button (void);
void fINIT_Lamp (void);

/* Global Declarations */

unsigned long time_ = 0;
struct tCHNOUT_mLampUnit CHNOUT_mLampUnit;
struct tTIMING_mLampUnit TIMING_mLampUnit;
struct tTMQE_mLampUnit *tuhead_mLampUnit, *tutail_mLampUnit;

/* Function Prototypes */

void fSETTIM_mLampUnit (unsigned long *delay_, struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_);
void fSTOPTIM_mLampUnit (struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_);
void fSTEP_(void);
void fCHAIN_(void);
void fTIMEUP_(void);
void fREAD_(void);

/* AUTO_ Handler Function */

static void fAUTOHDL_(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_(void)
{
	++time_;
	if (TIMING_mLampUnit.set_)
	{
		TIMING_mLampUnit.tkhndl_();
	}
}

void fSETTIM_mLampUnit (unsigned long *delay_, struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (!timer_->set_)
		{
			++TIMING_mLampUnit.set_;
		}
		timer_->set_ = TRUE;
		timer_->end_ = time_ + *delay_;
		if (tuhead_mLampUnit == timeup_)
		{
			tuhead_mLampUnit = tuhead_mLampUnit->next_;
		}
		if (timeup_->preced_)
		{
			timeup_->preced_->next_ = timeup_->next_;
		}
		if (timeup_->next_)
		{
			timeup_->next_->preced_ = timeup_->preced_;
		}
		if (tutail_mLampUnit == timeup_)
		{
			tutail_mLampUnit = timeup_->preced_;
		}
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
		{
			--TIMING_mLampUnit.set_;
		}
		timer_->set_ = FALSE;
		if (tuhead_mLampUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (!tuhead_mLampUnit)
			{
				tuhead_mLampUnit = tutail_mLampUnit = timeup_;
			}
			else 
			{
				tutail_mLampUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mLampUnit;
				tutail_mLampUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mLampUnit (struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_)
{
	if (timer_->set_)
	{
		--TIMING_mLampUnit.set_;
	}
	timer_->set_ = FALSE;
	if (tuhead_mLampUnit == timeup_)
	{
		tuhead_mLampUnit = tuhead_mLampUnit->next_;
	}
	if (timeup_->preced_)
	{
		timeup_->preced_->next_ = timeup_->next_;
	}
	if (timeup_->next_)
	{
		timeup_->next_->preced_ = timeup_->preced_;
	}
	if (tutail_mLampUnit == timeup_)
	{
		tutail_mLampUnit = timeup_->preced_;
	}
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_(void)
{
	if (tuhead_mLampUnit != 0)
	{
		TIMING_mLampUnit.tuhndl_();
	}
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_(void)
{
	if (tuhead_mLampUnit != 0)
	{
		TIMING_mLampUnit.tuhndl_();
	}
	return;
}

	/* Read Function for CIP Machine */

void fREAD_(void)
{
	return;
}


/* Initialization Function */

int fINIT_(void)
{
	tuhead_mLampUnit = tutail_mLampUnit = 0;
	TRG_.TICK_ = fTICK_;
	TRG_.CHAIN_ = fCHAIN_;
	TRG_.TIMEUP_ = fTIMEUP_;
	TRG_.STEP_ = fSTEP_;
	TRG_.READ_ = fREAD_;
	TRG_.AUTO_ = fAUTOHDL_;
	IN_.Button = fICHAN_Button;
	iCHAN_();
	if (!OUT_.Lamp)
	{
		return 0;
	}
	fINIT_Button ();
	fINIT_Lamp ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[a9fcef86-9d17-11e1-90e4-e1fd5739c0f6,dc0ccb3f-eeb2-11ef-a3fc-b5c521c52e06,bc124dc7-eea7-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,dc149378-eeb2-11ef-a3fc-b5c521c52e06,dc109bd3-eeb2-11ef-a3fc-b5c521c52e06,+rzQNjASavuhSMiAQkCNPDwUX9M=] */
