/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampImplementation
	Module for CIP SHELL sLampUnit
	Filename: sLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "sLampUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sLampUnit
*********************************************************************/

// Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,0e3da843-613c-11e2-8c6f-0d0126f0c0ea,16966e79-613e-11e2-8c6f-0d0126f0c0ea,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,16997bbd-613e-11e2-8c6f-0d0126f0c0ea,169c8802-613e-11e2-8c6f-0d0126f0c0ea,G7q3K5kApqRY4fYh9cFye/0GKeU=]
