/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION  LampImplementation
	Trace Interface Header File for CIP MACHINE mLampUnit
	Filename: tLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_tLampUnit_h_)
	#define _tLampUnit_h_

/* Text Switch Constants */

#if defined(_TRACE__)
	#undef _TRACE__
#endif

#if defined(_UT_INPUT_)
	#undef _UT_INPUT_
#endif

#if defined(_UT_OUTPUT_)
	#undef _UT_OUTPUT_
#endif

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mLampUnit.h"

#endif // _tLampUnit_h_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLampUnit
*********************************************************************/

// Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,0e3da843-613c-11e2-8c6f-0d0126f0c0ea,16966e79-613e-11e2-8c6f-0d0126f0c0ea,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,16997bbd-613e-11e2-8c6f-0d0126f0c0ea,H5mcBsCVspZwHo19jjOJXllSmUg=]
