/*********************************************************************
	SYSTEM Lamp_CipSystem
	IMPLEMENTATION  LampImplementation
	Trace Interface Header File for CIP MACHINE mLampUnit
	Filename: tLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_tLampUnit_h_)
	#define _tLampUnit_h_

/* Include Files */

#include "mLampUnit.h"

#endif // _tLampUnit_h_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLampUnit
*********************************************************************/

/* Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,dc0ccb3f-eeb2-11ef-a3fc-b5c521c52e06,bc124dc7-eea7-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,dc109bd3-eeb2-11ef-a3fc-b5c521c52e06,x+q7BXGwUlN7v0PnQXKnaown4aw=] */
