/*******************************************************************
        SYSTEM LampSystem
        Module for PROCESS Button
        Filename: Button.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LampSystemUnit 
        	enable PENDING_ information
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mLampSystemUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Button.write_access_
#define STATUS (pStatus_Button->read_access_)
#define TIME time_LampSystemUnit

/* Process Enumerations */

enum eMODES_Button
	{normal = 1};

enum eSTATES_Button
	{Pressed = 1, Released};


/* External Declarations */

extern unsigned char time_LampSystemUnit;
extern struct tCHNOUT_mLampSystemUnit CHNOUT_mLampSystemUnit;
void fUPDATE_LampCluster (void);
int fPULSE_Lamp (enum eOUTPLS_LampSystemUnit name_);

/* Global Declarations */

union tSTATUS_Button status_Button;
const union tSTATUS_Button *pStatus_Button = &status_Button;

/* Function Prototypes */

void fIMSG_C1_Press(void);
void fIMSG_C1_Release(void);
void fINIT_Button (void);

/* Input Channel Functions */

void fIMSG_C1_Press(void)
{
	switch(status_Button.read_access_.STATE)
	{
	case Released:
	 	status_Button.write_access_.STATE = Pressed;
	 	fPULSE_Lamp (O1_On);
		break;
	default:
		return;
	}
	fUPDATE_LampCluster ();
	return;
}

void fIMSG_C1_Release(void)
{
	switch(status_Button.read_access_.STATE)
	{
	case Pressed:
	 	status_Button.write_access_.STATE = Released;
	 	fPULSE_Lamp (O1_Off);
		break;
	default:
		return;
	}
	fUPDATE_LampCluster ();
	return;
}
		
/* Process Initialization Function */

void fINIT_Button (void)
{
	status_Button.write_access_.STATE = Released;
}		

/*********************************************************************
	End of Module for PROCESS Button
*********************************************************************/
// Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,a4ed7eae-45f8-11e2-a9e9-277eb93c19ba,afcc3dd0-45f8-11e2-a9e9-277eb93c19ba,55JYFlTnDXi5rx8sQuZ+uvKfdos=]
