/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampSystemImplementation
	Error Header File for CIP MACHINE mLampSystemUnit
	Filename: eLampSystemUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampSystemUnit 
		enable PENDING_ information
		'unsigned char' for delays
*********************************************************************/

#if !defined(_eLampSystemUnit_hLampSystemUnit_)
	#define _eLampSystemUnit_hLampSystemUnit_

/* Include Files */

#include "mLampSystemUnit.h"

#endif // _eLampSystemUnit_hLampSystemUnit_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLampSystemUnit
*********************************************************************/
// Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,o0wVZhhbX9X6vQoGGYY1qYXng2E=]
