/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampSystemImplementation
	Error Interface Module for CIP MACHINE mLampSystemUnit
	Filename: eLampSystemUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampSystemUnit 
		enable PENDING_ information
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "eLampSystemUnit.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mLampSystemUnit
*********************************************************************/

// Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,bQdsX+hduDUnFTjTtY9pAacgpgo=]
