/*******************************************************************
        SYSTEM LampSystem
        Module for PROCESS Lamp
        Filename: Lamp.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use message interface
        		naming option: use default prefix
        	use postfix
        		LampSystemUnit 
        	enable PENDING_ information
        	'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "mLampSystemUnit.h"

/* Process Macro Definitions */

#define SELF status_Lamp.write_access_
#define STATUS (pStatus_Lamp->read_access_)
#define TIME time_LampSystemUnit

/* Process Enumerations */

enum eMODES_Lamp
	{normal = 1};

enum eSTATES_Lamp
	{Bright = 1, Dark, Delayed};

enum eINPULS_Lamp
	{IP_On = 1, IP_Off = 2, TIMEUP_ = 3};
	

/* External Declarations */

extern unsigned char time_LampSystemUnit;
extern struct tTMQE_mLampSystemUnit *tuhead_mLampSystemUnit, *tutail_mLampSystemUnit;
extern struct tCHNOUT_mLampSystemUnit CHNOUT_mLampSystemUnit;
extern struct tTIMING_mLampSystemUnit TIMING_mLampSystemUnit;
void fUPDATE_LampCluster (void);
void fSETTIM_mLampSystemUnit (unsigned char *delay_, struct tTMEL_mLampSystemUnit *timer_, struct tTMQE_mLampSystemUnit *timeup_);
void fSTOPTIM_mLampSystemUnit (struct tTMEL_mLampSystemUnit *timer_, struct tTMQE_mLampSystemUnit *timeup_);

/* Global Declarations */

static unsigned char delay_;
struct tPRINST_Lamp IO_Lamp;
union tSTATUS_Lamp status_Lamp;
const union tSTATUS_Lamp *pStatus_Lamp = &status_Lamp;

/* Function Prototypes */

int fPULSE_Lamp (enum eOUTPLS_LampSystemUnit name_);
void fINIT_Lamp (void);

/* Input Channel Functions */

int fPULSE_Lamp (enum eOUTPLS_LampSystemUnit name_)
{
	switch(name_)
	{
		/* INPULSE On */
	case O1_On:		/* PULSE CAST from PROCESS Button */
		switch(status_Lamp.read_access_.STATE)
		{
		case Dark:
			status_Lamp.write_access_.STATE = Bright;
			CHNOUT_mLampSystemUnit.message_.CHAN_Lamp.name_ = C2_Bright;
			OUT_LampSystemUnit.C2_Bright ();
			break;
		case Delayed:
			status_Lamp.write_access_.STATE = Bright;
			fSTOPTIM_mLampSystemUnit(&IO_Lamp.timer_, 
				&IO_Lamp.timeup_);
			break;
		default:
			break;
		}
		break;
		/* INPULSE Off */
	case O1_Off:		/* PULSE CAST from PROCESS Button */
		switch(status_Lamp.read_access_.STATE)
		{
		case Bright:
			{
				delay_ =  1000;	/* DELAY delay */
				status_Lamp.write_access_.STATE = Delayed;
				fSETTIM_mLampSystemUnit(&delay_, 
					&IO_Lamp.timer_, 
					&IO_Lamp.timeup_);
			}
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Lamp (void)
{
	if (IO_Lamp.timer_.set_ &&
		IO_Lamp.timer_.end_ == time_LampSystemUnit)
	{
		IO_Lamp.timer_.set_ = FALSE;
		--TIMING_mLampSystemUnit.set_;
		if (tuhead_mLampSystemUnit != &IO_Lamp.timeup_ &&
			!IO_Lamp.timeup_.preced_ &&
			!IO_Lamp.timeup_.next_)
		{
			if (!tuhead_mLampSystemUnit)
			{
				tuhead_mLampSystemUnit = tutail_mLampSystemUnit = &IO_Lamp.timeup_;
			}
			else
			{
				tutail_mLampSystemUnit->next_ = &IO_Lamp.timeup_;
				IO_Lamp.timeup_.preced_ = tutail_mLampSystemUnit;
				tutail_mLampSystemUnit = &IO_Lamp.timeup_;
			}
		}
	}			
}

static void fTUHNDL_Lamp(void)
{
	struct tTMQE_mLampSystemUnit *element_ = tuhead_mLampSystemUnit;
	if (tuhead_mLampSystemUnit == tutail_mLampSystemUnit)
	{
		tuhead_mLampSystemUnit = tutail_mLampSystemUnit = 0;
	}
	else 
	{
		tuhead_mLampSystemUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mLampSystemUnit->preced_ = 0;
	}
	switch(status_Lamp.read_access_.STATE)
	{
	case Delayed:
		status_Lamp.write_access_.STATE = Dark;
		CHNOUT_mLampSystemUnit.message_.CHAN_Lamp.name_ = C2_Dark;
		OUT_LampSystemUnit.C2_Dark ();
		break;
	default:
		break;
	}
	fUPDATE_LampCluster ();
}

/* Process Initialization Function */

void fINIT_Lamp (void)
{
	status_Lamp.write_access_.STATE = Dark;
	IO_Lamp.timer_.set_ = FALSE;
	IO_Lamp.timeup_.preced_ = 0;
	IO_Lamp.timeup_.next_ = 0;
	IO_Lamp.timeup_.proctype_ = 0;
	TIMING_mLampSystemUnit.tkhndl_ = fTICK_Lamp;
	TIMING_mLampSystemUnit.tuhndl_ = fTUHNDL_Lamp;
}		

/*********************************************************************
	End of Module for PROCESS Lamp
*********************************************************************/
// Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,a4ed7eae-45f8-11e2-a9e9-277eb93c19ba,b2d05643-45f8-11e2-a9e9-277eb93c19ba,Ewva8ymMU8pq5P5xBSdcyySxtWA=]
