/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampSystemImplementation
	Header File for CIP MACHINE mLampSystemUnit
	Filename: mLampSystemUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampSystemUnit 
		enable PENDING_ information
		'unsigned char' for delays
*********************************************************************/

#if !defined(_mLampSystemUnit_hLampSystemUnit_)
	#define _mLampSystemUnit_hLampSystemUnit_

/* Include Files */

#include <stdlib.h>
#include "sLampSystemUnit.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Outpulse Types */
 
#if !defined(_eOUTPLS_LampSystemUnit_)
	#define _eOUTPLS_LampSystemUnit_

	enum eOUTPLS_LampSystemUnit
		{O1_On = 1, O1_Off = 2};

#endif // _eOUTPLS_LampSystemUnit_

struct tOUTPLS_Button
{
	enum eOUTPLS_LampSystemUnit name_;
};

union tOUTPLS_LampCluster
{
	struct tOUTPLS_Button OUTPLS_Button;
};

/* Global Output Type */

struct tCHAN_Lamp
{
	enum eMSG_Lamp name_;
};

union tCHAN_mLampSystemUnit
{
	struct tCHAN_Lamp CHAN_Lamp;
};

struct tCHNOUT_mLampSystemUnit
{
	union tCHAN_mLampSystemUnit message_;
};

/* Timer- and Queue-Element */

struct tTMEL_mLampSystemUnit
{
	unsigned char set_; /* Boolean */
	unsigned char end_;
};

struct tTMQE_mLampSystemUnit
{
	struct tTMQE_mLampSystemUnit *preced_;
	struct tTMQE_mLampSystemUnit *next_;
	int proctype_;
};

/* Global Table Elements */
struct tTIMING_mLampSystemUnit
{
	void  (*tkhndl_) (void);
	void (*tuhndl_)(void);
	int  set_;
};

/* Types for Process Button */

struct tPRSTAT_Button
{
	int STATE;
};

union tSTATUS_Button
{
	struct tPRSTAT_Button write_access_;
	struct tPRSTAT_Button read_access_;
};

/* Types for Process Lamp */

struct tPRSTAT_Lamp
{
	int STATE;
};

union tSTATUS_Lamp
{
	struct tPRSTAT_Lamp write_access_;
	struct tPRSTAT_Lamp read_access_;
};

struct tPRINST_Lamp
{
	struct tTMEL_mLampSystemUnit timer_;
	struct tTMQE_mLampSystemUnit timeup_;
};

#endif // _mLampSystemUnit_hLampSystemUnit_

/*********************************************************************
	End of Header File for CIP MACHINE mLampSystemUnit
*********************************************************************/
// Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,53507b87-45fa-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,8mpZnimHU2cWlCNxgez3U9TpgbM=]
