/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampSystemImplementation
	Module for CIP SHELL sLampSystemUnit
	Filename: sLampSystemUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampSystemUnit 
		enable PENDING_ information
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "sLampSystemUnit.h"

/* Input Interface */

struct tIN_LampSystemUnit IN_LampSystemUnit;

/* Output Interface */

struct tOUT_LampSystemUnit OUT_LampSystemUnit;

/* Trigger Interface */

struct tTRG_LampSystemUnit TRG_LampSystemUnit;

/*********************************************************************
	End of Module for CIP SHELL sLampSystemUnit
*********************************************************************/

// Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,53507b87-45fa-11e2-a9e9-277eb93c19ba,zlRXTdWAf32hxVIph3YljCvThtA=]
