/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION  LampSystemImplementation
	Trace Interface Header File for CIP MACHINE mLampSystemUnit
	Filename: tLampSystemUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampSystemUnit 
		enable PENDING_ information
		'unsigned char' for delays
*********************************************************************/

#if !defined(_tLampSystemUnit_hLampSystemUnit_)
	#define _tLampSystemUnit_hLampSystemUnit_

/* Text Switch Constants */

#if defined(_TRACE__)
	#undef _TRACE__
#endif

#if defined(_UT_INPUT_)
	#undef _UT_INPUT_
#endif

#if defined(_UT_OUTPUT_)
	#undef _UT_OUTPUT_
#endif

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mLampSystemUnit.h"

#endif // _tLampSystemUnit_hLampSystemUnit_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLampSystemUnit
*********************************************************************/

// Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,nrzLL2w5m5jXy8nCGofCNkIFA44=]
