/*********************************************************************
	SYSTEM LampSystem
	IMPLEMENTATION LampSystemImplementation
	Trace Interface Module for CIP MACHINE mLampSystemUnit
	Filename: tLampSystemUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use message interface
			naming option: use default prefix
		use postfix
			LampSystemUnit 
		enable PENDING_ information
		'unsigned char' for delays
*********************************************************************/

/* Include Files */

#include "tLampSystemUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLampSystemUnit
*********************************************************************/
// Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,47a975e5-45f8-11e2-a9e9-277eb93c19ba,534e318e-45fa-11e2-a9e9-277eb93c19ba,7884c17a-45fb-11e2-a9e9-277eb93c19ba,534f9122-45fa-11e2-a9e9-277eb93c19ba,Y20+uRvV4wUPdt04I82ylyYqAwc=]
