/*******************************************************************
        SYSTEM Test_CipSystem
        Module for PROCESS Lamp
        Filename: Lamp.c
        generated by CIP Tool(R)

        activated code options:
        	C code
        	use channel interface
        		naming option: use default prefix
        	'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "mLampUnit.h"

/* Process Macro Definitions */

#define SELF status_Lamp.write_access_
#define STATUS (pStatus_Lamp->read_access_)
#define TIME time_

/* Process Enumerations */

enum eMODES_Lamp
	{normal = 1};

enum eSTATES_Lamp
	{Bright = 1, Dark, Delayed};

enum eINPULS_Lamp
	{IP_On = 1, IP_Off, TIMEUP_};
	

/* External Declarations */

extern unsigned long time_;
extern struct tTMQE_mLampUnit *tuhead_mLampUnit, *tutail_mLampUnit;
extern struct tCHNOUT_mLampUnit CHNOUT_mLampUnit;
extern struct tTIMING_mLampUnit TIMING_mLampUnit;
void fSETTIM_mLampUnit (unsigned long *delay_, struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_);
void fSTOPTIM_mLampUnit (struct tTMEL_mLampUnit *timer_, struct tTMQE_mLampUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Lamp IO_Lamp;
union tSTATUS_Lamp status_Lamp;
const union tSTATUS_Lamp *pStatus_Lamp = &status_Lamp;

/* Function Prototypes */

int fPULSE_Lamp (enum eOUTPLS_ name_);
void fINIT_Lamp (void);

/* Input Channel Functions */

int fPULSE_Lamp (enum eOUTPLS_ name_)
{
	switch(name_)
	{
		/* INPULSE On */
	case O1_On:		/* PULSE CAST from PROCESS Button */
		switch(status_Lamp.read_access_.STATE)
		{
		case Dark:
			status_Lamp.write_access_.STATE = Bright;
			CHNOUT_mLampUnit.message_.CHAN_Lamp.name_ = C2_Bright;
			OUT_.Lamp(CHNOUT_mLampUnit.message_.CHAN_Lamp.name_);
			break;
		case Delayed:
			status_Lamp.write_access_.STATE = Bright;
			break;
		default:
			break;
		}
		break;
		/* INPULSE Off */
	case O1_Off:		/* PULSE CAST from PROCESS Button */
		switch(status_Lamp.read_access_.STATE)
		{
		case Bright:
			{
				delay_ =  3;	/* DELAY 3 */
				status_Lamp.write_access_.STATE = Delayed;
				fSETTIM_mLampUnit(&delay_, 
					&IO_Lamp.timer_, 
					&IO_Lamp.timeup_);
			}
			break;
		default:
			break;
		}
		break;
	default:
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Lamp (void)
{
	if (IO_Lamp.timer_.set_ &&
		IO_Lamp.timer_.end_ == time_)
	{
		IO_Lamp.timer_.set_ = FALSE;
		--TIMING_mLampUnit.set_;
		if (tuhead_mLampUnit != &IO_Lamp.timeup_ &&
			!IO_Lamp.timeup_.preced_ &&
			!IO_Lamp.timeup_.next_)
		{
			if (!tuhead_mLampUnit)
			{
				tuhead_mLampUnit = tutail_mLampUnit = &IO_Lamp.timeup_;
			}
			else
			{
				tutail_mLampUnit->next_ = &IO_Lamp.timeup_;
				IO_Lamp.timeup_.preced_ = tutail_mLampUnit;
				tutail_mLampUnit = &IO_Lamp.timeup_;
			}
		}
	}			
}

static void fTUHNDL_Lamp(void)
{
	struct tTMQE_mLampUnit *element_ = tuhead_mLampUnit;
	if (tuhead_mLampUnit == tutail_mLampUnit)
	{
		tuhead_mLampUnit = tutail_mLampUnit = 0;
	}
	else 
	{
		tuhead_mLampUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mLampUnit->preced_ = 0;
	}
	switch(status_Lamp.read_access_.STATE)
	{
	case Delayed:
		status_Lamp.write_access_.STATE = Dark;
		CHNOUT_mLampUnit.message_.CHAN_Lamp.name_ = C2_Dark;
		OUT_.Lamp(CHNOUT_mLampUnit.message_.CHAN_Lamp.name_);
		break;
	default:
		break;
	}
}

/* Process Initialization Function */

void fINIT_Lamp (void)
{
	status_Lamp.write_access_.STATE = Dark;
	IO_Lamp.timer_.set_ = FALSE;
	IO_Lamp.timeup_.preced_ = 0;
	IO_Lamp.timeup_.next_ = 0;
	IO_Lamp.timeup_.proctype_ = 0;
	TIMING_mLampUnit.tkhndl_ = fTICK_Lamp;
	TIMING_mLampUnit.tuhndl_ = fTUHNDL_Lamp;
}		

/*********************************************************************
	End of Module for PROCESS Lamp
*********************************************************************/
/* Actifsource ID=[e9267837-2596-11e1-ae2f-a14f3e396de6,44cac99a-eebb-11ef-a3fc-b5c521c52e06,44cac947-eebb-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,44cac998-eebb-11ef-a3fc-b5c521c52e06,44cac997-eebb-11ef-a3fc-b5c521c52e06,44cac98d-eebb-11ef-a3fc-b5c521c52e06,IfVUKA8vu4MJFzeL2KN9x7FnD1A=] */
