/*********************************************************************
  SYSTEM Test_CipSystem
  IMPLEMENTATION LampImplementation
  Error Header File for CIP MACHINE mLampUnit
  Filename: mainTest_CipSystem_TestSuite_Console.h
  generated by CIP Tool(R)
  
  activated code options:
  	C code
  	use channel interface
  		naming option: use default prefix
  	'unsigned long' for delays
*********************************************************************/


#ifndef _MAIN_H
#define _MAIN_H

/* === INCLUDE FILES =============================================================== */
#include "sLampUnit.h"

/* === TYPEs =============================================================== */
/** Enum to specify the animation mode. */
typedef enum EAnimationMode
{
  eAnimationMode_Undefined,
  eAnimationMode_Manual,
  eAnimationMode_Regressive,
  eAnimationMode_Runner
} T_EAnimationMode;

/**
 * Returns the current animation mode.
 */
T_EAnimationMode Main_getAnimationMode(void);

#endif // _MAIN_H

/* Actifsource ID=[146c2b3d-30d5-11e7-a447-9b7f17a8ec30,6fe21579-eeba-11ef-a3fc-b5c521c52e06,dnpQWXz6R7OrPwUIVX++DYU6jDk=] */
