/*********************************************************************
	SYSTEM Test_CipSystem
	IMPLEMENTATION LampImplementation
	Header File for CIP MACHINE mLampUnit
	Filename: mLampUnit.h
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_mLampUnit_h_)
	#define _mLampUnit_h_

/* Include Files */

#include <stdlib.h>
#include "sLampUnit.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Outpulse Types */
 
#if !defined(_eOUTPLS__)
	#define _eOUTPLS__

	enum eOUTPLS_
		{/* LampCluster */ O1_On = 1, O1_Off};

#endif // _eOUTPLS__

struct tOUTPLS_Button
{
	enum eOUTPLS_ name_;
};

union tOUTPLS_LampCluster
{
	struct tOUTPLS_Button OUTPLS_Button;
};

/* Global Output Type */

struct tCHAN_Lamp
{
	enum eMSG_Lamp name_;
};

union tCHAN_mLampUnit
{
	struct tCHAN_Lamp CHAN_Lamp;
};

struct tCHNOUT_mLampUnit
{
	union tCHAN_mLampUnit message_;
};

/* Timer- and Queue-Element */

struct tTMEL_mLampUnit
{
	unsigned char set_; /* Boolean */
	unsigned long end_;
};

struct tTMQE_mLampUnit
{
	struct tTMQE_mLampUnit *preced_;
	struct tTMQE_mLampUnit *next_;
	int proctype_;
};

/* Global Table Elements */
struct tTIMING_mLampUnit
{
	void  (*tkhndl_) (void);
	void (*tuhndl_)(void);
	int  set_;
};

/* Types for Process Button */

struct tPRSTAT_Button
{
	int STATE;
};

union tSTATUS_Button
{
	struct tPRSTAT_Button write_access_;
	struct tPRSTAT_Button read_access_;
};

/* Types for Process Lamp */

struct tPRSTAT_Lamp
{
	int STATE;
};

union tSTATUS_Lamp
{
	struct tPRSTAT_Lamp write_access_;
	struct tPRSTAT_Lamp read_access_;
};

struct tPRINST_Lamp
{
	struct tTMEL_mLampUnit timer_;
	struct tTMQE_mLampUnit timeup_;
};

#endif // _mLampUnit_h_

/*********************************************************************
	End of Header File for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,44cac99a-eebb-11ef-a3fc-b5c521c52e06,44cac947-eebb-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,44cac999-eebb-11ef-a3fc-b5c521c52e06,44cac998-eebb-11ef-a3fc-b5c521c52e06,qaIgZ+ak6R3hz4lxyp8SW+ylPcE=] */
