/*********************************************************************
	SYSTEM Test_CipSystem
	IMPLEMENTATION LampImplementation
	Module for CIP SHELL sLampUnit
	Filename: sLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "sLampUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sLampUnit
*********************************************************************/

/* Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,44cac99a-eebb-11ef-a3fc-b5c521c52e06,44cac947-eebb-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,44cac998-eebb-11ef-a3fc-b5c521c52e06,44cac999-eebb-11ef-a3fc-b5c521c52e06,FC+c7eHAgWfPJ75rnFqgLITa+oY=] */
