/*********************************************************************
	SYSTEM Test_CipSystem
	IMPLEMENTATION LampImplementation
	Trace Interface Module for CIP MACHINE mLampUnit
	Filename: tLampUnit.c
	generated by CIP Tool(R)
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "tLampUnit.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLampUnit
*********************************************************************/
/* Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,44cac99a-eebb-11ef-a3fc-b5c521c52e06,44cac947-eebb-11ef-a3fc-b5c521c52e06,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,44cac998-eebb-11ef-a3fc-b5c521c52e06,WFqRpvzMyg/UNJgxxlhM1lqScMM=] */
