
/*********************************************************************
	SYSTEM System1
	IMPLEMENTATION Lamp
	Error Interface Module for CIP MACHINE mLamp
	Filename: eLamp.c
	generated by CIP Tool(R) Version 1.0.0
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "eLamp.h"
/*********************************************************************
	End of Error Interface Module for CIP MACHINE mLamp
*********************************************************************/

// Actifsource ID=[43cc81df-9d17-11e1-90e4-e1fd5739c0f6,c78073c1-af0f-11e1-8e28-c3261f5498f2,4971106d-af26-11e1-8e28-c3261f5498f2,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,4977c731-af26-11e1-8e28-c3261f5498f2,OQ9wsSQzQnSllY0woeVluq8PTxo=]
