
/*********************************************************************
	SYSTEM System1
	IMPLEMENTATION Lamp
	Error Header File for CIP MACHINE mLamp
	Filename: eLamp.h
	generated by CIP Tool(R) Version 1.0.0
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_eLamp_h_)
	#define _eLamp_h_

/* Include Files */

#include "mLamp.h"

#endif // _eLamp_h_

/*********************************************************************
	End of Error Header File for CIP MACHINE mLamp
*********************************************************************/
// Actifsource ID=[fa1b3c54-2630-11e1-b9e3-e1fa7eef1208,c78073c1-af0f-11e1-8e28-c3261f5498f2,4971106d-af26-11e1-8e28-c3261f5498f2,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,4977c731-af26-11e1-8e28-c3261f5498f2,AzSuhE/yOfYqX7R+lwgUQ13RzwE=]
