
/*********************************************************************
	SYSTEM System1
	IMPLEMENTATION Lamp
	Header File for CIP MACHINE mLamp
	Filename: mLamp.h
	generated by CIP Tool(R) Version 1.0.0
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_mLamp_h_)
	#define _mLamp_h_

/* Include Files */

#include <stdlib.h>
#include "sLamp.h"

/* Macro Definitions */

#if !defined(FALSE)
	#define FALSE 0
#endif // FALSE

#if !defined(TRUE)
	#define TRUE 1
#endif // TRUE

/* Outpulse Types */
 
#if !defined(_eOUTPLS__)
	#define _eOUTPLS__

	enum eOUTPLS_
		{O1_On = 1, O1_Off = 2};

#endif // _eOUTPLS__

struct tOUTPLS_Button
{
	enum eOUTPLS_ name_;
};

union tOUTPLS_Lamp
{
	struct tOUTPLS_Button OUTPLS_Button;
};

/* Global Output Type */

struct tCHAN_Lamp
{
	enum eMSG_Lamp name_;
};

union tCHAN_mLamp
{
	struct tCHAN_Lamp CHAN_Lamp;
};

struct tCHNOUT_mLamp
{
	union tCHAN_mLamp message_;
};

/* Timer- and Queue-Element */

struct tTMEL_mLamp
{
	unsigned char set_; /* Boolean */
	unsigned long end_;
};

struct tTMQE_mLamp
{
	struct tTMQE_mLamp *preced_;
	struct tTMQE_mLamp *next_;
	int proctype_;
};

/* Global Table Elements */
struct tTIMING_mLamp
{
	void  (*tkhndl_) (void);
	void (*tuhndl_)(void);
	int  set_;
};

/* Types for Process Button */

struct tPRSTAT_Button
{
	int STATE;
};

union tSTATUS_Button
{
	struct tPRSTAT_Button write_access_;
	struct tPRSTAT_Button read_access_;
};

/* Types for Process Lamp */

struct tPRSTAT_Lamp
{
	int STATE;
};

union tSTATUS_Lamp
{
	struct tPRSTAT_Lamp write_access_;
	struct tPRSTAT_Lamp read_access_;
};

struct tPRINST_Lamp
{
	struct tTMEL_mLamp timer_;
	struct tTMQE_mLamp timeup_;
};

#endif // _mLamp_h_

/*********************************************************************
	End of Header File for CIP MACHINE mLamp
*********************************************************************/
// Actifsource ID=[79d4b5d7-259a-11e1-ae2f-a14f3e396de6,c78073c1-af0f-11e1-8e28-c3261f5498f2,4971106d-af26-11e1-8e28-c3261f5498f2,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,49794dd6-af26-11e1-8e28-c3261f5498f2,4977c731-af26-11e1-8e28-c3261f5498f2,lo+Rb0wKaQdJhs70urKbXFBkmMg=]
