
/*********************************************************************
	SYSTEM System1
	IMPLEMENTATION Lamp
	Module for CIP SHELL sLamp
	Filename: sLamp.c
	generated by CIP Tool(R) Version 1.0.0
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "sLamp.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sLamp
*********************************************************************/

// Actifsource ID=[c73316db-9d1a-11e1-90e4-e1fd5739c0f6,c78073c1-af0f-11e1-8e28-c3261f5498f2,4971106d-af26-11e1-8e28-c3261f5498f2,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,4977c731-af26-11e1-8e28-c3261f5498f2,49794dd6-af26-11e1-8e28-c3261f5498f2,9/vI31gMIUuAIm7v8HX3KZhqij4=]
