
/*********************************************************************
	SYSTEM System1
	IMPLEMENTATION Lamp
	Trace Interface Module for CIP MACHINE mLamp
	Filename: tLamp.c
	generated by CIP Tool(R) Version 1.0.0
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

/* Include Files */

#include "tLamp.h"
/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mLamp
*********************************************************************/
// Actifsource ID=[c86244d2-259a-11e1-ae2f-a14f3e396de6,c78073c1-af0f-11e1-8e28-c3261f5498f2,4971106d-af26-11e1-8e28-c3261f5498f2,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,4977c731-af26-11e1-8e28-c3261f5498f2,I3BfLuRvZcTR6yqB8CN2MRjdsVI=]
