
/*********************************************************************
	SYSTEM System1
	IMPLEMENTATION  Lamp
	Trace Interface Header File for CIP MACHINE mLamp
	Filename: tLamp.h
	generated by CIP Tool(R) Version 1.0.0
	
	activated code options:
		C code
		use channel interface
			naming option: use default prefix
		'unsigned long' for delays
*********************************************************************/

#if !defined(_tLamp_h_)
	#define _tLamp_h_

/* Text Switch Constants */

#if defined(_TRACE__)
	#undef _TRACE__
#endif

#if defined(_UT_INPUT_)
	#undef _UT_INPUT_
#endif

#if defined(_UT_OUTPUT_)
	#undef _UT_OUTPUT_
#endif

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mLamp.h"

#endif // _tLamp_h_

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mLamp
*********************************************************************/

// Actifsource ID=[1cfc7444-9d1b-11e1-90e4-e1fd5739c0f6,c78073c1-af0f-11e1-8e28-c3261f5498f2,4971106d-af26-11e1-8e28-c3261f5498f2,ba697f7b-2723-11e1-b14b-53cb3f44a5b8,4977c731-af26-11e1-8e28-c3261f5498f2,tEin5Y7lcUOQc4S47UCRk6MVXwE=]
